from pyco import terminal, cursor
from time import sleep
import this

terminal.set_window_title("Pyco Demo")
sleep(0.5)
terminal.bell()
sleep(0.5)
terminal.scroll_up()
sleep(0.5)
terminal.scroll_down()
sleep(0.5)
cursor.line_up(5)
sleep(0.5)
cursor.right(5)
sleep(0.5)
terminal.clear_line(0)
sleep(0.5)
cursor.up()
sleep(0.5)
terminal.clear_line(1)
sleep(0.5)
cursor.up()
sleep(0.5)
terminal.clear_line(2)
sleep(0.5)
terminal.alt_screen_buffer()
sleep(0.5)
print("Text in the alternate screen buffer")
sleep(0.5)
terminal.main_screen_buffer()
sleep(0.5)
print("Text in the main screen buffer")
sleep(0.5)
terminal.clear_screen()
