from pyco.color import Fore, Back, Style

print(Fore.BLACK   + "Fore.BLACK  " + "\t\t" + Fore.BRIGHT_BLACK   + "Fore.BRIGHT_BLACK  " + Style.RESET)
print(Fore.RED     + "Fore.RED    " + "\t\t" + Fore.BRIGHT_RED     + "Fore.BRIGHT_RED    " + Style.RESET)
print(Fore.GREEN   + "Fore.GREEN  " + "\t\t" + Fore.BRIGHT_GREEN   + "Fore.BRIGHT_GREEN  " + Style.RESET)
print(Fore.YELLOW  + "Fore.YELLOW " + "\t\t" + Fore.BRIGHT_YELLOW  + "Fore.BRIGHT_YELLOW " + Style.RESET)
print(Fore.BLUE    + "Fore.BLUE   " + "\t\t" + Fore.BRIGHT_BLUE    + "Fore.BRIGHT_BLUE   " + Style.RESET)
print(Fore.MAGENTA + "Fore.MAGENTA" + "\t\t" + Fore.BRIGHT_MAGENTA + "Fore.BRIGHT_MAGENTA" + Style.RESET)
print(Fore.CYAN    + "Fore.CYAN   " + "\t\t" + Fore.BRIGHT_CYAN    + "Fore.BRIGHT_CYAN   " + Style.RESET)
print(Fore.WHITE   + "Fore.WHITE  " + "\t\t" + Fore.BRIGHT_WHITE   + "Fore.BRIGHT_WHITE  " + Style.RESET)
print(Fore.DEFAULT + "Fore.DEFAULT" + Style.RESET)
print()
print(Back.BLACK   + "Back.BLACK  " + "\t\t" + Back.BRIGHT_BLACK   + "Back.BRIGHT_BLACK  " + Style.RESET)
print(Back.RED     + "Back.RED    " + "\t\t" + Back.BRIGHT_RED     + "Back.BRIGHT_RED    " + Style.RESET)
print(Back.GREEN   + "Back.GREEN  " + "\t\t" + Back.BRIGHT_GREEN   + "Back.BRIGHT_GREEN  " + Style.RESET)
print(Back.YELLOW  + "Back.YELLOW " + "\t\t" + Back.BRIGHT_YELLOW  + "Back.BRIGHT_YELLOW " + Style.RESET)
print(Back.BLUE    + "Back.BLUE   " + "\t\t" + Back.BRIGHT_BLUE    + "Back.BRIGHT_BLUE   " + Style.RESET)
print(Back.MAGENTA + "Back.MAGENTA" + "\t\t" + Back.BRIGHT_MAGENTA + "Back.BRIGHT_MAGENTA" + Style.RESET)
print(Back.CYAN    + "Back.CYAN   " + "\t\t" + Back.BRIGHT_CYAN    + "Back.BRIGHT_CYAN   " + Style.RESET)
print(Back.WHITE   + "Back.WHITE  " + "\t\t" + Back.BRIGHT_WHITE   + "Back.BRIGHT_WHITE  " + Style.RESET)
print(Back.DEFAULT + "Back.DEFAULT" + Style.RESET)
